### ISSUE TITLE
FBA to FBN

### ISSUE THREAD

**Issue by 7zxkv** [jhawkzz/FBAlpha-Shock#12]
Hi jhawkzz. 

I have a question for you:
could you tell me why you don't use FBN instead of FBA which is now obsolete (no longer recognized by the official team) while the code base is still very close?

Otherwise, at worst, it might be easier to use the FBN driver files (in drv) rather than trying to update the FBA ones, the format being totally identical. Let's take a simple example at random: this would allow your mvsx compilation to run samsh5fe and samsh5pf which are not functional or non-existent in your version!  (and that it would be legitimate to add)

Otherwise thank you for what you do. best regards

**Comment by jhawkzz** [comment]
> Hi jhawkzz.
> 
> I have a question for you: could you tell me why you don't use FBN instead of FBA which is now obsolete (no longer recognized by the official team) while the code base is still very close?
> 
> Otherwise, at worst, it might be easier to use the FBN driver files (in drv) rather than trying to update the FBA ones, the format being totally identical. Let's take a simple example at random: this would allow your mvsx compilation to run samsh5fe and samsh5pf which are not functional or non-existent in your version! (and that it would be legitimate to add)
> 
> Otherwise thank you for what you do. best regards

Hi!

Thanks for the feedback and kind words. The immediate reason I didn't use FBN is to minimize the number of unknowns as I developed for MVSX. I knew with certainty FBA worked, and although the FBN code is similar, there are enough changes in it to introduce potential issues.

That said, once FBA Shock gets into a stable state, I do intend to evaluate updating it to be FBN.

FWIW, I did pull in SamSho 5 Perfect support from FBN into FBA Shock. So, there's that :)

**Comment by jhawkzz** [comment]
@7zxkv Thanks for explaining! I had it backwards in my head and thought SS5 Perfect was the "official" version. Yes, I will make sure this is added to the next release :)

**Comment by jhawkzz** [comment]
@7zxkv Added support in this commit - https://github.com/jhawkzz/FBAlpha-Shock/commit/5c18537d9b448f76feb517fa86187fe89eb78bd8

**Comment by 7zxkv** [comment]
thanks to you !
